### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tora1000** [tora1000/furima-31081#10]
フリマアプリのURL: https://furima-31081.herokuapp.com/

Basic認証のIDとパスワード:
ID:tora  
パスワード:1000

出品者用のメールアドレスとパスワード:
アドレス:kota19980114@gmail.com 
パスワード:kota1998

購入者用のメールアドレスとパスワード
アドレス:kei@kei 
パスワード:kei1000

購入用カードの番号・期限・セキュリティコード
番号:4242424242424242
期限:12月22年
セキュリティコード:123

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
